### ISSUE TITLE
Information about aria-labelledby

### ISSUE THREAD

**Issue by Tklaversma** [leungwensen/svg-icon#16]
According to various [resources](https://bugs.chromium.org/p/chromium/issues/detail?id=566252) (this is just one about the Chrome), adding `aria-labelledby` to the `<symbol>` in the SVG makes sure the `title`-attribute will be read by modern browsers.

But actually adding content to `aria-labelledby` is not necessary. Screenreader will read the `<title>`-attribute and skip the content of `aria-labelledby`.

Therefor, the content of `aria-labelledby` can be empty.

**Comment by leungwensen** [comment]
Good point!

**Comment by leungwensen** [comment]
Now you have `<title>` and `aria-labelledby` in `<symbol>` e90896953e2f6dc2fbb0804fca592bd608e5cd35
