### ISSUE TITLE
svg images are not displaying on web page

### ISSUE THREAD

**Issue by vishalbiradar** [leungwensen/svg-icon#43]
I have just downloaded ant-appstore svg image from ant-design from your site and then copy-pasted that image in my assets/images folder.

`<img src="assets/images/si-sprite.svg" width="26" height="26">`

But it is showing nothing on the web page.

What extra things I required in order to make those SVG images visible on the web page.

**Comment by leungwensen** [comment]
An SVG sprite file contains a series of SVG icon definitions, which are references to SVG icons, not real visible icons.  https://css-tricks.com/svg-sprites-use-better-icon-fonts/

Using an SVG sprite is like follows:

```html
<svg><use xlink:href="assets/images/si-sprite.svg#${id}"></use></svg>
```

**Comment by vishalbiradar** [comment]
Thanks a lot...
