### ISSUE TITLE
Cannot open any svg file in svg tools like Inkscape

### ISSUE THREAD

**Issue by cyberb** [leungwensen/svg-icon#45]
Should I be able to open these svg files in tools like Inkscape?

**Comment by leungwensen** [comment]
those files downloaded from https://leungwensen.github.io/svg-icon/ are SVG sprite files, icons defined in those files is just symbols, not visible paths. if what you want are visible SVG icons, you can find them here:  https://github.com/leungwensen/svg-icon/tree/master/dist/svg
